classdef TemperatureScoreConfig < SBTi.configs.PortfolioAggregationConfig
    
    % This factor determines what part of the temperature for a not SBTi-validated company should be the TS and what part
    % should be the default score.
    
    properties
        SBTi_FACTOR = 1
        FILE_SR15_MAPPING = fullfile( extractBefore(mfilename('fullpath'), 'TemperatureScoreConfig'), "inputs", "sr15_mapping.xlsx")
        FILE_REGRESSION_MODEL_SUMMARY = fullfile( extractBefore(mfilename('fullpath'), 'TemperatureScoreConfig'), "inputs", "regression_model_summary.xlsx")
        
        DEFAULT_INDUSTRY = "Others"
        
        VALUE_TARGET_REFERENCE_ABSOLUTE = "absolute"
        VALUE_TARGET_REFERENCE_INTENSITY = "intensity"
        VALUE_TARGET_REFERENCE_INTENSITY_BASE = "int"
        
        SLOPE_MAP = struct( ...
            SBTi.interfaces.ETimeFrames.SHORT, "slope5", ...
            SBTi.interfaces.ETimeFrames.MID, "slope15", ...
            SBTi.interfaces.ETimeFrames.LONG, "slope30");
        
        INTENSITY_MAPPINGS = struct(...
            "Revenue", containers.Map([SBTi.interfaces.EScope.S1S2, SBTi.interfaces.EScope.S3], ["INT.emKyoto_gdp", "INT.emKyoto_gdp"]) , ...
            "Product", containers.Map([SBTi.interfaces.EScope.S1S2, SBTi.interfaces.EScope.S3], ["INT.emKyoto_gdp", "INT.emKyoto_gdp"]) , ...
            "Cement",  containers.Map([SBTi.interfaces.EScope.S1S2, SBTi.interfaces.EScope.S3], ["INT.emKyoto_gdp", "INT.emKyoto_gdp"]) , ...
            "Oil",     containers.Map([SBTi.interfaces.EScope.S1S2, SBTi.interfaces.EScope.S3], ["INT.emCO2EI_PE", "INT.emCO2EI_PE"]), ...
            "Steel",   containers.Map([SBTi.interfaces.EScope.S1S2, SBTi.interfaces.EScope.S3], ["INT.emKyoto_gdp", "INT.emKyoto_gdp"]), ...
            "Aluminum",containers.Map([SBTi.interfaces.EScope.S1S2, SBTi.interfaces.EScope.S3], ["INT.emKyoto_gdp", "INT.emKyoto_gdp"]) ,...
            "Power",   containers.Map([SBTi.interfaces.EScope.S1S2, SBTi.interfaces.EScope.S3], ["INT.emCO2EI_elecGen", "INT.emCO2EI_elecGen"]) ...
        );
        
        ABSOLUTE_MAPPINGS = struct( ...
            "B06", containers.Map([SBTi.interfaces.EScope.S1S2, SBTi.interfaces.EScope.S3], ["Emissions|Kyoto Gases", "Emissions|Kyoto Gases"]), ...
            "C23", containers.Map([SBTi.interfaces.EScope.S1S2, SBTi.interfaces.EScope.S3], ["Emissions|CO2|Energy and Industrial Processes", "Emissions|Kyoto Gases"]), ...
            "C24", containers.Map([SBTi.interfaces.EScope.S1S2, SBTi.interfaces.EScope.S3], ["Emissions|CO2|Energy and Industrial Processes", "Emissions|Kyoto Gases"]), ...
            "D35", containers.Map([SBTi.interfaces.EScope.S1S2, SBTi.interfaces.EScope.S3], ["Emissions|CO2|Energy and Industrial Processes", "Emissions|Kyoto Gases"]), ...
            "H49", containers.Map([SBTi.interfaces.EScope.S1S2, SBTi.interfaces.EScope.S3], ["Emissions|Kyoto Gases", "Emissions|Kyoto Gases"]), ...
            "H50", containers.Map([SBTi.interfaces.EScope.S1S2, SBTi.interfaces.EScope.S3], ["Emissions|Kyoto Gases", "Emissions|Kyoto Gases"]), ...
            "H51", containers.Map([SBTi.interfaces.EScope.S1S2, SBTi.interfaces.EScope.S3], ["Emissions|Kyoto Gases", "Emissions|Kyoto Gases"]), ...
            "H52", containers.Map([SBTi.interfaces.EScope.S1S2, SBTi.interfaces.EScope.S3], ["Emissions|Kyoto Gases", "Emissions|Kyoto Gases"]), ...
            "H53", containers.Map([SBTi.interfaces.EScope.S1S2, SBTi.interfaces.EScope.S3], ["Emissions|Kyoto Gases", "Emissions|Kyoto Gases"]), ...
            "other", containers.Map([SBTi.interfaces.EScope.S1S2, SBTi.interfaces.EScope.S3], ["Emissions|Kyoto Gases", "Emissions|Kyoto Gases"]) ...
            );
        
        TEMPERATURE_RESULTS = 'temperature_results'
        INVESTMENT_VALUE = "investment_value"
    end
end